### ISSUE TITLE
Refactor Switch puzzle to use base class

### ISSUE THREAD

**Issue by Bailey-W** [DeltaGroupSWE/DeltaMain#58]

**Comment by dakotaSicher** [comment]
switch puzzle refactored to use base class, working with the test file showPuzzleWEBGL.js but seems to be a conflict with cube file, need to investigate

**Comment by dakotaSicher** [comment]
conflict with cubeMain.js resolved by moving preload stuff to cubeMain.js

**Comment by dbabusci** [comment]
Added some polish to it
