### ISSUE TITLE
slider puzzle uses image

### ISSUE THREAD

**Issue by dakotaSicher** [DeltaGroupSWE/DeltaMain#92]
slider puzzle should display an image that for the player to arrange correctly instead of the tile designations

done: 
when tiles display correct portion of image instead of tile numbers

**Comment by sidneyraabe** [comment]
Just added images. They are located in:

assets->sprites->slider-images

the file names correspond to the piece map in the puzzle js

**Comment by dakotaSicher** [comment]
*villain pose* excellent
